/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warteg;

import javax.swing.JOptionPane;
import java.text.*;
import java.util.*;
import javafx.util.*;

/**
 *
 * @author MILLENIA SAHARANI
 */
public class Order extends javax.swing.JFrame {

    String nama, NoMeja,catatan ,bayar,kembalian,total,qnasi, jnasi, qayam, jayam, qkerang, jkerang, qatiampela, jatiampela, qcumi, jcumi, qikan, jikan, qkentang,jkentang,
                qempal, jempal,qudang,judang,qairmineral,jairmineral,qteh,jteh,qkopi,jkopi,qkerupuk,jkerupuk,qgorengan,jgorengan;
    
    private static ArrayList<String> pesanan = new ArrayList<>();
    
    private static ArrayList<String> order = new ArrayList<>();
    
    int harga[]={3000,8000,3000,4000,7000,10000,4000,9000,7000,1000,3000,4000,1000,2000}, totalharga;
    
    String Menu[]={"Nasi","Ayam Goreng","Tumis Kerang","Oseng Ati Ampela","Cumi Saus Tiram","Pesmol Ikan","Kentang Balado","Empal Geprek","Udang Goreng","Air Mineral","Teh Tawar/Manis","Kopi","Kerupuk","Gorengan"};
    
    List<Pair<String, String>> list = new ArrayList<>();
   
    public Order() {
        initComponents();
    }
    
    public static List<String> getList(){
        return order;
    }
    
    public static List<String> getList2(){
        return pesanan;
    }

    
    public Order(ArrayList<String> p){
       initComponents();
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        chkAyam = new javax.swing.JCheckBox();
        chkKerang = new javax.swing.JCheckBox();
        chkAtiAmpela = new javax.swing.JCheckBox();
        chkCumi = new javax.swing.JCheckBox();
        chkIkan = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        qtyKerang = new javax.swing.JTextField();
        qtyAtiAmpela = new javax.swing.JTextField();
        qtyCumi = new javax.swing.JTextField();
        qtyIkan = new javax.swing.JTextField();
        jmlAyam = new javax.swing.JTextField();
        jmlKerang = new javax.swing.JTextField();
        jmlAtiAmpela = new javax.swing.JTextField();
        jmlCumi = new javax.swing.JTextField();
        jmlIkan = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        chkAirMineral = new javax.swing.JCheckBox();
        chkTeh = new javax.swing.JCheckBox();
        chkKopi = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        chkKerupuk = new javax.swing.JCheckBox();
        chkGorengan = new javax.swing.JCheckBox();
        qtyAirMineral = new javax.swing.JTextField();
        qtyTeh = new javax.swing.JTextField();
        qtyKopi = new javax.swing.JTextField();
        jmlAirMineral = new javax.swing.JTextField();
        jmlTeh = new javax.swing.JTextField();
        jmlKopi = new javax.swing.JTextField();
        qtyKerupuk = new javax.swing.JTextField();
        qtyGorengan = new javax.swing.JTextField();
        jmlKerupuk = new javax.swing.JTextField();
        jmlGorengan = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        chkKentang = new javax.swing.JCheckBox();
        chkEmpal = new javax.swing.JCheckBox();
        qtyKentang = new javax.swing.JTextField();
        qtyEmpal = new javax.swing.JTextField();
        jmlKentang = new javax.swing.JTextField();
        jmlEmpal = new javax.swing.JTextField();
        chkUdang = new javax.swing.JCheckBox();
        qtyUdang = new javax.swing.JTextField();
        jmlUdang = new javax.swing.JTextField();
        chkNasi = new javax.swing.JCheckBox();
        jmlNasi = new javax.swing.JTextField();
        qtyNasi = new javax.swing.JTextField();
        qtyAyam = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbJumlahOrang = new javax.swing.JComboBox<String>();
        cmbMeja = new javax.swing.JComboBox<String>();
        jLabel9 = new javax.swing.JLabel();
        txtNoPesanan = new javax.swing.JTextField();
        txtAtasNama = new javax.swing.JTextField();
        btnPesan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        lblKembali = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnNota = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCatatan = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableNota = new javax.swing.JTable();
        btnHitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MAKANAN");

        chkAyam.setText("Ayam Goreng (Rp 8.000)");
        chkAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAyamActionPerformed(evt);
            }
        });

        chkKerang.setText("Tumis Kerang (Rp 3.000)");
        chkKerang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkKerangActionPerformed(evt);
            }
        });

        chkAtiAmpela.setText("Oseng Ati Ampela (Rp 4.000)");
        chkAtiAmpela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAtiAmpelaActionPerformed(evt);
            }
        });

        chkCumi.setText("Cumi Saus Tiram (Rp 7.000)");
        chkCumi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCumiActionPerformed(evt);
            }
        });

        chkIkan.setText("Pesmol Ikan (Rp 10.000)");
        chkIkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIkanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Qty");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Jumlah");

        qtyKerang.setEditable(false);
        qtyKerang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtyKerang.setText("0");
        qtyKerang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyKerangKeyReleased(evt);
            }
        });

        qtyAtiAmpela.setEditable(false);
        qtyAtiAmpela.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtyAtiAmpela.setText("0");
        qtyAtiAmpela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyAtiAmpelaKeyReleased(evt);
            }
        });

        qtyCumi.setEditable(false);
        qtyCumi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtyCumi.setText("0");
        qtyCumi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyCumiKeyReleased(evt);
            }
        });

        qtyIkan.setEditable(false);
        qtyIkan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtyIkan.setText("0");
        qtyIkan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyIkanKeyReleased(evt);
            }
        });

        jmlAyam.setEditable(false);
        jmlAyam.setBackground(new java.awt.Color(232, 236, 241));
        jmlAyam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmlAyam.setText("0");

        jmlKerang.setEditable(false);
        jmlKerang.setBackground(new java.awt.Color(232, 236, 241));
        jmlKerang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmlKerang.setText("0");

        jmlAtiAmpela.setEditable(false);
        jmlAtiAmpela.setBackground(new java.awt.Color(232, 236, 241));
        jmlAtiAmpela.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmlAtiAmpela.setText("0");

        jmlCumi.setEditable(false);
        jmlCumi.setBackground(new java.awt.Color(232, 236, 241));
        jmlCumi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmlCumi.setText("0");

        jmlIkan.setEditable(false);
        jmlIkan.setBackground(new java.awt.Color(232, 236, 241));
        jmlIkan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmlIkan.setText("0");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("MINUMAN");

        chkAirMineral.setText("Air Mineral (Rp 1.000)");
        chkAirMineral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAirMineralActionPerformed(evt);
            }
        });

        chkTeh.setText("Teh Tawar/Manis (Rp 3.000)");
        chkTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTehActionPerformed(evt);
            }
        });

        chkKopi.setText("Kopi (Rp 4.000)");
        chkKopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkKopiActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("TAMBAHAN");

        chkKerupuk.setText("Kerupuk (Rp 1.000)");
        chkKerupuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkKerupukActionPerformed(evt);
            }
        });

        chkGorengan.setText("Gorengan (Rp 2.000)");
        chkGorengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkGorenganActionPerformed(evt);
            }
        });

        qtyAirMineral.setEditable(false);
        qtyAirMineral.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtyAirMineral.setText("0");
        qtyAirMineral.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyAirMineralKeyReleased(evt);
            }
        });

        qtyTeh.setEditable(false);
        qtyTeh.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtyTeh.setText("0");
        qtyTeh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyTehKeyReleased(evt);
            }
        });

        qtyKopi.setEditable(false);
        qtyKopi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtyKopi.setText("0");
        qtyKopi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyKopiKeyReleased(evt);
            }
        });

        jmlAirMineral.setEditable(false);
        jmlAirMineral.setBackground(new java.awt.Color(232, 236, 241));
        jmlAirMineral.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmlAirMineral.setText("0");

        jmlTeh.setEditable(false);
        jmlTeh.setBackground(new java.awt.Color(232, 236, 241));
        jmlTeh.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmlTeh.setText("0");

        jmlKopi.setEditable(false);
        jmlKopi.setBackground(new java.awt.Color(232, 236, 241));
        jmlKopi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmlKopi.setText("0");

        qtyKerupuk.setEditable(false);
        qtyKerupuk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtyKerupuk.setText("0");
        qtyKerupuk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyKerupukKeyReleased(evt);
            }
        });

        qtyGorengan.setEditable(false);
        qtyGorengan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtyGorengan.setText("0");
        qtyGorengan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyGorenganKeyReleased(evt);
            }
        });

        jmlKerupuk.setEditable(false);
        jmlKerupuk.setBackground(new java.awt.Color(232, 236, 241));
        jmlKerupuk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmlKerupuk.setText("0");

        jmlGorengan.setEditable(false);
        jmlGorengan.setBackground(new java.awt.Color(232, 236, 241));
        jmlGorengan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmlGorengan.setText("0");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Jumlah");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Qty");

        chkKentang.setText("Kentang Balado (Rp 4.000)");
        chkKentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkKentangActionPerformed(evt);
            }
        });

        chkEmpal.setText("Empal Geprek (Rp 9.000)");
        chkEmpal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEmpalActionPerformed(evt);
            }
        });

        qtyKentang.setEditable(false);
        qtyKentang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtyKentang.setText("0");
        qtyKentang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyKentangKeyReleased(evt);
            }
        });

        qtyEmpal.setEditable(false);
        qtyEmpal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtyEmpal.setText("0");
        qtyEmpal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyEmpalKeyReleased(evt);
            }
        });

        jmlKentang.setEditable(false);
        jmlKentang.setBackground(new java.awt.Color(232, 236, 241));
        jmlKentang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmlKentang.setText("0");

        jmlEmpal.setEditable(false);
        jmlEmpal.setBackground(new java.awt.Color(232, 236, 241));
        jmlEmpal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmlEmpal.setText("0");

        chkUdang.setText("Udang Goreng Tepung (Rp 7.000)");
        chkUdang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkUdangActionPerformed(evt);
            }
        });

        qtyUdang.setEditable(false);
        qtyUdang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtyUdang.setText("0");
        qtyUdang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyUdangKeyReleased(evt);
            }
        });

        jmlUdang.setEditable(false);
        jmlUdang.setBackground(new java.awt.Color(232, 236, 241));
        jmlUdang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmlUdang.setText("0");

        chkNasi.setText("Nasi (Rp 3.000)");
        chkNasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNasiActionPerformed(evt);
            }
        });

        jmlNasi.setEditable(false);
        jmlNasi.setBackground(new java.awt.Color(232, 236, 241));
        jmlNasi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmlNasi.setText("0");

        qtyNasi.setEditable(false);
        qtyNasi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtyNasi.setText("0");
        qtyNasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyNasiKeyReleased(evt);
            }
        });

        qtyAyam.setEditable(false);
        qtyAyam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtyAyam.setText("0");
        qtyAyam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyAyamKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Qty");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Jumlah");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkCumi)
                        .addComponent(chkKerang)
                        .addComponent(chkIkan)
                        .addComponent(chkKentang)
                        .addComponent(chkEmpal)
                        .addComponent(jLabel1)
                        .addComponent(chkAyam)
                        .addComponent(chkNasi)
                        .addComponent(chkAtiAmpela)
                        .addComponent(chkUdang, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel17)
                        .addComponent(chkAirMineral))
                    .addComponent(chkTeh)
                    .addComponent(chkKopi)
                    .addComponent(jLabel18)
                    .addComponent(chkKerupuk)
                    .addComponent(chkGorengan))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(qtyGorengan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jmlKentang)
                                .addComponent(jmlIkan)
                                .addComponent(jmlCumi)
                                .addComponent(jmlAtiAmpela)
                                .addComponent(jmlAyam)
                                .addComponent(jmlEmpal)
                                .addComponent(jmlKerang)
                                .addComponent(jmlUdang)
                                .addComponent(jmlAirMineral)
                                .addComponent(jmlTeh)
                                .addComponent(jmlKopi)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jmlGorengan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmlKerupuk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(qtyUdang)
                            .addComponent(qtyKentang)
                            .addComponent(qtyCumi)
                            .addComponent(qtyAtiAmpela)
                            .addComponent(qtyKerang)
                            .addComponent(qtyNasi)
                            .addComponent(qtyAyam)
                            .addComponent(qtyIkan)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(qtyEmpal)
                            .addComponent(qtyAirMineral)
                            .addComponent(qtyKopi)
                            .addComponent(qtyTeh)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jmlNasi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(qtyKerupuk, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(48, 48, 48)
                            .addComponent(jmlAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jmlKerang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jmlAtiAmpela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jmlCumi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jmlIkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jmlKentang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jmlEmpal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jmlUdang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52)
                            .addComponent(jmlAirMineral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jmlTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jmlKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(qtyNasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkNasi)
                                .addComponent(jmlNasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(qtyAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkAyam))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(qtyKerang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkKerang))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(qtyAtiAmpela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkAtiAmpela))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(qtyCumi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkCumi))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(qtyIkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkIkan))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(qtyKentang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkKentang))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(qtyEmpal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkEmpal))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(qtyUdang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkUdang))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(jLabel20)
                                .addComponent(jLabel17))
                            .addGap(11, 11, 11)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(qtyAirMineral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkAirMineral))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(qtyTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkTeh))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(qtyKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkKopi))))
                    .addComponent(jLabel1))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel21)
                    .addComponent(jLabel18))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmlGorengan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyKerupuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkKerupuk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmlKerupuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyGorengan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkGorengan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Atas Nama :");

        jLabel6.setText("Nomor Meja :");

        jLabel7.setText("Jumlah Orang :");

        cmbJumlahOrang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1-2 Orang", "3-4 Orang", "5-6 Orang", ">6 Orang" }));

        cmbMeja.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Meja 1", "Meja 2", "Meja 3", "Meja 4", "Meja 5", "Meja 6", "Meja 7", "Meja 8", "Meja 9", "Meja 10" }));
        cmbMeja.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setText("Nomor Pesanan :");

        txtNoPesanan.setEditable(false);
        txtNoPesanan.setBackground(new java.awt.Color(232, 236, 241));
        txtNoPesanan.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnPesan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPesan.setText("PESAN");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNoPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAtasNama, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbJumlahOrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesan))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNoPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAtasNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbJumlahOrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 246, 143));

        jLabel8.setFont(new java.awt.Font("Ink Free", 1, 34)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 120, 75));
        jLabel8.setText("FOOD COURT CASHIER");

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogout))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
            .addComponent(lblLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(241, 169, 160));
        jPanel4.setPreferredSize(new java.awt.Dimension(500, 90));

        jLabel10.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(150, 40, 27));
        jLabel10.setText("MENU ITEM");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(129, 207, 224));

        jLabel11.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(58, 83, 155));
        jLabel11.setText("RESERVASI");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(213, 184, 255));

        jLabel2.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(103, 65, 114));
        jLabel2.setText("TRANSAKSI");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(108, 108, 108))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setText("Total :");

        jLabel13.setText("Bayar :");

        jLabel14.setText("Kembali :");

        txtBayar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBayarKeyReleased(evt);
            }
        });

        lblKembali.setText("Rp 0.");

        btnProses.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnProses.setText("PROSES");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnNota.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNota.setText("NOTA");
        btnNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotaActionPerformed(evt);
            }
        });

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(232, 236, 241));
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.setText("0");

        jLabel16.setText("Catatan :");

        txtCatatan.setColumns(20);
        txtCatatan.setRows(5);
        jScrollPane1.setViewportView(txtCatatan);

        TableNota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Item", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TableNota);

        btnHitung.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblKembali)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(btnProses)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblKembali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal)
                    .addComponent(btnProses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNota, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public String clearorder()
    {
        txtAtasNama.setText(null);
            chkNasi.setSelected(false);
            qtyNasi.setText("0");
            jmlNasi.setText("0");
            chkAyam.setSelected(false);
            qtyAyam.setText("0");
            jmlAyam.setText("0");
            chkKerang.setSelected(false);
            qtyKerang.setText("0");
            jmlKerang.setText("0");
            chkAtiAmpela.setSelected(false);
            qtyAtiAmpela.setText("0");
            jmlAtiAmpela.setText("0");
            chkCumi.setSelected(false);
            qtyCumi.setText("0");
            jmlCumi.setText("0");
            chkIkan.setSelected(false);
            qtyIkan.setText("0");
            jmlIkan.setText("0");
            chkKentang.setSelected(false);
            qtyKentang.setText("0");
            jmlKentang.setText("0");
            chkEmpal.setSelected(false);
            qtyEmpal.setText("0");
            jmlEmpal.setText("0");
            chkUdang.setSelected(false);
            qtyUdang.setText("0");
            jmlUdang.setText("0");
            chkAirMineral.setSelected(false);
            qtyAirMineral.setText("0");
            jmlAirMineral.setText("0");
            chkTeh.setSelected(false);
            qtyTeh.setText("0");
            jmlTeh.setText("0");
            chkKopi.setSelected(false);
            qtyKopi.setText("0");
            jmlKopi.setText("0");
            chkKerupuk.setSelected(false);
            qtyKerupuk.setText("0");
            jmlKerupuk.setText("0");
            chkGorengan.setSelected(false);
            qtyGorengan.setText("0");
            jmlGorengan.setText("0");
            txtTotal.setText("0");
            txtBayar.setText(null);
            lblKembali.setText("Rp 0.");
            txtCatatan.setText(null);
            return null;
    }
    public int hitungair(int qtyair) {
        
       int jumlahair = qtyair*harga[9];
        jmlAirMineral.setText(Integer.toString(jumlahair));
        return jumlahair;
    }
    
    public float Total(int nasi,int ayam, int kerang, int ati, int cumi, int ikan, int kentang, int empal, int udang, int air, int teh, int kopi, int kerupuk, int gorengan){
       totalharga = nasi + ayam + kerang + ati + cumi + ikan + kentang + empal + udang + air + teh + kopi + kerupuk + gorengan;
        txtTotal.setText(Integer.toString(totalharga));
        return totalharga;
    }
    
    public float kembalian(float bayar, float total) {
        float kembali = bayar - total;
        lblKembali.setText(Float.toString(kembali));
        DecimalFormat angka = new DecimalFormat("###,###");
        lblKembali.setText("Rp "+angka.format(kembali));
        return kembali;
    }
    
    public int hitungteh(int qtyteh) {
        int jumlahteh = qtyteh*harga[10];
        jmlTeh.setText(Integer.toString(jumlahteh));
        return jumlahteh;
    }
    
    public int hitungnasi(int qtynasi){
        int jumlahnasi = qtynasi*harga[0];
        jmlNasi.setText(Integer.toString(jumlahnasi));
        return jumlahnasi;
    }
    public int hitungayam(int qtyayam){
        int jumlahayam = qtyayam*harga[1];
        jmlAyam.setText(Integer.toString(jumlahayam));  
        return jumlahayam;
    }
    public int hitungkerang(int qtykerang){
        int jumlahkerang = qtykerang*harga[2];
        jmlKerang.setText(Integer.toString(jumlahkerang));    
        return jumlahkerang;
    }
    public int hitungati(int qtyati){
        int jumlahatiampela = qtyati*harga[3];
        jmlAtiAmpela.setText(Integer.toString(jumlahatiampela));   
        return jumlahatiampela;
    }
    public int hitungcumi(int qtycumi){
        int jumlahcumi = qtycumi*harga[4];
        jmlCumi.setText(Integer.toString(jumlahcumi));
        return jumlahcumi;
    }
    public int hitungikan(int qtyikan){
        int jumlahikan = qtyikan*harga[5];
        jmlIkan.setText(Integer.toString(jumlahikan));
        return jumlahikan;
    }
    public int hitungkentang( int qtykentang){
        int jumlahkentang = qtykentang*harga[6];
        jmlKentang.setText(Integer.toString(jumlahkentang));
        return jumlahkentang;
    }
    public int hitungempal(int qtyempal){
        int jumlahempal = qtyempal*harga[7];
        jmlEmpal.setText(Integer.toString(jumlahempal));   
        return jumlahempal;
    }
    public int hitungudang(int qtyudang){
        int jumlahudang = qtyudang*harga[8];
        jmlUdang.setText(Integer.toString(jumlahudang));
        return jumlahudang;
    }
    public int hitungkopi(int qtykopi){
        int jumlahkopi = qtykopi*harga[11];
        jmlKopi.setText(Integer.toString(jumlahkopi));   
        return jumlahkopi;
    }
    public int hitungkerupuk(int qtykerupuk){
        int jumlahkerupuk = qtykerupuk*harga[12];
        jmlKerupuk.setText(Integer.toString(jumlahkerupuk));   
        return jumlahkerupuk;
    }
    public int hitunggorengan(int qtygorengan){
        int jumlahgorengan = qtygorengan*harga[13];
        jmlGorengan.setText(Integer.toString(jumlahgorengan));   
        return jumlahgorengan;
    }
    private void qtyUdangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyUdangKeyReleased
        int udang = Integer.parseInt(qtyUdang.getText());
        hitungudang(udang);
    }//GEN-LAST:event_qtyUdangKeyReleased

    private void qtyEmpalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyEmpalKeyReleased
        int empal = Integer.parseInt(qtyEmpal.getText());
        hitungempal(empal);
    }//GEN-LAST:event_qtyEmpalKeyReleased

    private void qtyKentangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKentangKeyReleased
        int kentang = Integer.parseInt(qtyKentang.getText());
        hitungkentang(kentang);
    }//GEN-LAST:event_qtyKentangKeyReleased

    private void qtyIkanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyIkanKeyReleased
                int ikan = Integer.parseInt(qtyIkan.getText());
        hitungikan(ikan);
    }//GEN-LAST:event_qtyIkanKeyReleased

    private void qtyCumiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyCumiKeyReleased
        int cumi = Integer.parseInt(qtyCumi.getText());
        hitungcumi(cumi);
    }//GEN-LAST:event_qtyCumiKeyReleased

    private void qtyAtiAmpelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyAtiAmpelaKeyReleased
        int ati = Integer.parseInt(qtyAtiAmpela.getText());
        hitungati(ati);
    }//GEN-LAST:event_qtyAtiAmpelaKeyReleased

    private void qtyKerangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKerangKeyReleased
        int kerang = Integer.parseInt(qtyKerang.getText());
        hitungkerang(kerang);
    }//GEN-LAST:event_qtyKerangKeyReleased

    private void qtyAyamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyAyamKeyReleased
        int ayam = Integer.parseInt(qtyAyam.getText());
        hitungayam(ayam);
    }//GEN-LAST:event_qtyAyamKeyReleased

    private void qtyNasiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyNasiKeyReleased
        int nasi = Integer.parseInt(qtyNasi.getText());
        hitungnasi(nasi);
    }//GEN-LAST:event_qtyNasiKeyReleased

    private void qtyAirMineralKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyAirMineralKeyReleased
        int air = Integer.parseInt(qtyAirMineral.getText());
        hitungair(air);
    }//GEN-LAST:event_qtyAirMineralKeyReleased

    private void qtyTehKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTehKeyReleased
        int teh = Integer.parseInt(qtyTeh.getText());
        hitungteh(teh);
    }//GEN-LAST:event_qtyTehKeyReleased

    private void qtyKopiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKopiKeyReleased
        int kopi = Integer.parseInt(qtyKopi.getText());
        hitungkopi(kopi);
    }//GEN-LAST:event_qtyKopiKeyReleased

    private void qtyKerupukKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKerupukKeyReleased
        int kerupuk = Integer.parseInt(qtyKerupuk.getText());
        hitungkerupuk(kerupuk);
    }//GEN-LAST:event_qtyKerupukKeyReleased

    private void qtyGorenganKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyGorenganKeyReleased
        int gorengan = Integer.parseInt(qtyGorengan.getText());
        hitunggorengan(gorengan);
    }//GEN-LAST:event_qtyGorenganKeyReleased

    private void chkNasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNasiActionPerformed
        if (chkNasi.isSelected()){
            qtyNasi.setEditable(true);
            qtyNasi.setText("");
        } else {
            qtyNasi.setEditable(false);
            qtyNasi.setText("0");
            jmlNasi.setText("0");
        }
    }//GEN-LAST:event_chkNasiActionPerformed

    private void chkAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAyamActionPerformed
        if (chkAyam.isSelected()){
            qtyAyam.setEditable(true);
            qtyAyam.setText("");
        } else {
            qtyAyam.setEditable(false);
            qtyAyam.setText("0");
            jmlAyam.setText("0");
        }
    }//GEN-LAST:event_chkAyamActionPerformed

    private void chkKerangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKerangActionPerformed
        if (chkKerang.isSelected()){
            qtyKerang.setEditable(true);
            qtyKerang.setText("");
        } else {
            qtyKerang.setEditable(false);
            qtyKerang.setText("0");
            jmlKerang.setText("0");
        }
    }//GEN-LAST:event_chkKerangActionPerformed

    private void chkAtiAmpelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAtiAmpelaActionPerformed
        if (chkAtiAmpela.isSelected()){
            qtyAtiAmpela.setEditable(true);
            qtyAtiAmpela.setText("");
        } else {
            qtyAtiAmpela.setEditable(false);
            qtyAtiAmpela.setText("0");
            jmlAtiAmpela.setText("0");
        }
    }//GEN-LAST:event_chkAtiAmpelaActionPerformed

    private void chkCumiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCumiActionPerformed
        if (chkCumi.isSelected()){
            qtyCumi.setEditable(true);
            qtyCumi.setText("");
        } else {
            qtyCumi.setEditable(false);
            qtyCumi.setText("0");
            jmlCumi.setText("0");
        }
    }//GEN-LAST:event_chkCumiActionPerformed

    private void chkIkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIkanActionPerformed
        if (chkIkan.isSelected()){
            qtyIkan.setEditable(true);
            qtyIkan.setText("");
        } else {
            qtyIkan.setEditable(false);
            qtyIkan.setText("0");
            jmlIkan.setText("0");
        }
    }//GEN-LAST:event_chkIkanActionPerformed

    private void chkKentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKentangActionPerformed
        if (chkKentang.isSelected()){
            qtyKentang.setEditable(true);
            qtyKentang.setText("");
        } else {
            qtyKentang.setEditable(false);
            qtyKentang.setText("0");
            jmlKentang.setText("0");
        }
    }//GEN-LAST:event_chkKentangActionPerformed

    private void chkEmpalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEmpalActionPerformed
        if (chkEmpal.isSelected()){
            qtyEmpal.setEditable(true);
            qtyEmpal.setText("");
        } else {
            qtyEmpal.setEditable(false);
            qtyEmpal.setText("0");
            jmlEmpal.setText("0");
        }
    }//GEN-LAST:event_chkEmpalActionPerformed

    private void chkUdangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkUdangActionPerformed
        if (chkUdang.isSelected()){
            qtyUdang.setEditable(true);
            qtyUdang.setText("");
        } else {
            qtyUdang.setEditable(false);
            qtyUdang.setText("0");
            jmlUdang.setText("0");
        }
    }//GEN-LAST:event_chkUdangActionPerformed

    private void chkAirMineralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAirMineralActionPerformed
        if (chkAirMineral.isSelected()){
            qtyAirMineral.setEditable(true);
            qtyAirMineral.setText("");
        } else {
            qtyAirMineral.setEditable(false);
            qtyAirMineral.setText("0");
            jmlAirMineral.setText("0");
        }
    }//GEN-LAST:event_chkAirMineralActionPerformed

    private void chkTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTehActionPerformed
        if (chkTeh.isSelected()){
            qtyTeh.setEditable(true);
            qtyTeh.setText("");
        } else {
            qtyTeh.setEditable(false);
            qtyTeh.setText("0");
            jmlTeh.setText("0");
        }
    }//GEN-LAST:event_chkTehActionPerformed

    private void chkKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKopiActionPerformed
        if (chkKopi.isSelected()){
            qtyKopi.setEditable(true);
            qtyKopi.setText("");
        } else {
            qtyKopi.setEditable(false);
            qtyKopi.setText("0");
            jmlKopi.setText("0");
        }
    }//GEN-LAST:event_chkKopiActionPerformed

    private void chkKerupukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKerupukActionPerformed
        if (chkKerupuk.isSelected()){
            qtyKerupuk.setEditable(true);
            qtyKerupuk.setText("");
        } else {
            qtyKerupuk.setEditable(false);
            qtyKerupuk.setText("0");
            jmlKerupuk.setText("0");
        }
    }//GEN-LAST:event_chkKerupukActionPerformed

    private void chkGorenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGorenganActionPerformed
        if (chkGorengan.isSelected()){
            qtyGorengan.setEditable(true);
            qtyGorengan.setText("");
        } else {
            qtyGorengan.setEditable(false);
            qtyGorengan.setText("0");
            jmlGorengan.setText("0");
        }
    }//GEN-LAST:event_chkGorenganActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        int dialog = JOptionPane.showOptionDialog(this, "Anda yakin ingin membatalkan pesanan?", "Batal", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
    
        if(dialog == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Pesanan dibatalkan");
            clearorder();
        }
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        int nasi = Integer.parseInt(jmlNasi.getText());
        int ayam = Integer.parseInt(jmlAyam.getText());
        int kerang = Integer.parseInt(jmlKerang.getText());
        int ati = Integer.parseInt(jmlAtiAmpela.getText());
        int cumi = Integer.parseInt(jmlCumi.getText());
        int ikan = Integer.parseInt(jmlIkan.getText());
        int kentang = Integer.parseInt(jmlKentang.getText());
        int empal = Integer.parseInt(jmlEmpal.getText());
        int udang = Integer.parseInt(jmlUdang.getText());
        int air = Integer.parseInt(jmlAirMineral.getText());
        int teh = Integer.parseInt(jmlTeh.getText());
        int kopi = Integer.parseInt(jmlKopi.getText());
        int kerupuk = Integer.parseInt(jmlKerupuk.getText());
        int gorengan = Integer.parseInt(jmlGorengan.getText());    
        Total(nasi,ayam,kerang,ati,cumi,ikan,kentang,empal,udang,air,teh,kopi,kerupuk,gorengan);
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        nama = txtAtasNama.getText();
        NoMeja = cmbMeja.getSelectedItem().toString();
        int qnasi1 = Integer.parseInt(qtyNasi.getText());
        qnasi = (qtyNasi.getText());
        jnasi = (jmlNasi.getText());
        int qayam1 = Integer.parseInt(qtyAyam.getText());
        qayam = (qtyAyam.getText());
        jayam = (jmlAyam.getText());
        int qkerang1 = Integer.parseInt(qtyKerang.getText());
        qkerang = (qtyKerang.getText());
        jkerang = (jmlKerang.getText());
        int qatiampela1 = Integer.parseInt(qtyAtiAmpela.getText());
        qatiampela = (qtyAtiAmpela.getText());
        jatiampela = (jmlAtiAmpela.getText());
        int qcumi1 = Integer.parseInt(qtyCumi.getText());
        qcumi = (qtyCumi.getText());
        jcumi = (jmlCumi.getText());
        int qikan1 = Integer.parseInt(qtyIkan.getText());
        qikan = (qtyIkan.getText());
        jikan = jmlIkan.getText();
        int qkentang1 = Integer.parseInt(qtyKentang.getText());
        qkentang = (qtyKentang.getText());
        jkentang = (jmlKentang.getText());
        int qempal1 = Integer.parseInt(qtyEmpal.getText());
        qempal = (qtyEmpal.getText());
        jempal = (jmlEmpal.getText());
        int qudang1 = Integer.parseInt(qtyUdang.getText());
        qudang = (qtyUdang.getText());
        judang = (jmlUdang.getText());
        int qairmineral1 = Integer.parseInt(qtyAirMineral.getText());
        qairmineral = (qtyAirMineral.getText());
        jairmineral = (jmlAirMineral.getText());
        int qteh1 = Integer.parseInt(qtyTeh.getText());
        qteh = (qtyTeh.getText());
        jteh = (jmlTeh.getText());
        int qkopi1 = Integer.parseInt(qtyKopi.getText());
        qkopi = (qtyKopi.getText());
        jkopi = (jmlKopi.getText());
        int qkerupuk1 = Integer.parseInt(qtyKerupuk.getText());
        qkerupuk = (qtyKerupuk.getText());
        jkerupuk = (jmlKerupuk.getText());
        int qgorengan1 = Integer.parseInt(qtyGorengan.getText());
        qgorengan = (qtyGorengan.getText());
        jgorengan = (jmlGorengan.getText());
        total = txtTotal.getText();
        bayar = txtBayar.getText();
        kembalian = lblKembali.getText();
        catatan = txtCatatan.getText();
        order.add(nama);
        order.add(NoMeja);        
        order.add(qnasi);        
        order.add(qayam);        
        order.add(qkerang);        
        order.add(qatiampela);        
        order.add(qcumi);        
        order.add(qikan);        
        order.add(qkentang);
        order.add(qempal);
        order.add(qudang);
        order.add(qairmineral);
        order.add(qteh);
        order.add(qkopi);
        order.add(qkerupuk);
        order.add(qgorengan);
        order.add(total);
        order.add(bayar);
        order.add(kembalian);
        order.add(catatan);
        String border = null;
        int DialogButton = JOptionPane.showConfirmDialog(this, "Silahkan Konfirmasi Pesanan Anda"+ "\nNama : " + order.get(0) +"\nNo. Meja : "+order.get(1)+ "\nNasi : " + order.get(2) + "\nAyam : " + order.get(3)+"\nKerang : "+order.get(4)+"\nAti Ampela : "+order.get(5)
        +"\nCumi : "+order.get(6)+"\nIkan : "+order.get(7)+"\nKentang : "+order.get(8)+"\nEmpal : "+order.get(9)+"\nUdang : "+order.get(10)+"\nAir : "+order.get(11)+"\nTeh : "+order.get(12)+"\nKopi : "+order.get(12)
        +"\nKerupuk : "+order.get(14)+"\nGorengan : "+order.get(15)+"\nTotal : "+order.get(16)+"\nBayar : " + order.get(17) +"\nKembali : "+order.get(18)+"\nCatatan : "+order.get(19));
        switch(DialogButton){
            case JOptionPane.YES_OPTION :
                pesanan.add(order.toString());
                txtAtasNama.setText(null);
                chkNasi.setSelected(false);
                qtyNasi.setText("0");
                jmlNasi.setText("0");
                chkAyam.setSelected(false);
                qtyAyam.setText("0");
                jmlAyam.setText("0");
                chkKerang.setSelected(false);
                qtyKerang.setText("0");
                jmlKerang.setText("0");
                chkAtiAmpela.setSelected(false);
                qtyAtiAmpela.setText("0");
                jmlAtiAmpela.setText("0");
                chkCumi.setSelected(false);
                qtyCumi.setText("0");
                jmlCumi.setText("0");
                chkIkan.setSelected(false);
                qtyIkan.setText("0");
                jmlIkan.setText("0");
                chkKentang.setSelected(false);
                qtyKentang.setText("0");
                jmlKentang.setText("0");
                chkEmpal.setSelected(false);
                qtyEmpal.setText("0");
                jmlEmpal.setText("0");
                chkUdang.setSelected(false);
                qtyUdang.setText("0");
                jmlUdang.setText("0");
                chkAirMineral.setSelected(false);
                qtyAirMineral.setText("0");
                jmlAirMineral.setText("0");
                chkTeh.setSelected(false);
                qtyTeh.setText("0");
                jmlTeh.setText("0");
                chkKopi.setSelected(false);
                qtyKopi.setText("0");
                jmlKopi.setText("0");
                chkKerupuk.setSelected(false);
                qtyKerupuk.setText("0");
                jmlKerupuk.setText("0");
                chkGorengan.setSelected(false);
                qtyGorengan.setText("0");
                jmlGorengan.setText("0");
                txtTotal.setText("0");
                txtBayar.setText(null);
                lblKembali.setText("Rp 0.");
                txtCatatan.setText(null);
                JOptionPane.showMessageDialog(this, "Pesanan akan kami proses");
                tampil();
            break;
        }
    }//GEN-LAST:event_btnProsesActionPerformed
    
    private void txtBayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBayarKeyReleased
        kembalian(Float.parseFloat(txtBayar.getText()), totalharga);
    }//GEN-LAST:event_txtBayarKeyReleased
    
    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        if (txtAtasNama != null) {
        int billNumber = pesanan.size()+1;
        String s = Integer.toString(billNumber++);
        txtNoPesanan.setText("ORD"+s);}
    }//GEN-LAST:event_btnPesanActionPerformed

    private void btnNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotaActionPerformed
        this.dispose();
        new Nota().setVisible(true);
    }//GEN-LAST:event_btnNotaActionPerformed
   

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableNota;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnNota;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btnProses;
    private javax.swing.JCheckBox chkAirMineral;
    private javax.swing.JCheckBox chkAtiAmpela;
    private javax.swing.JCheckBox chkAyam;
    private javax.swing.JCheckBox chkCumi;
    private javax.swing.JCheckBox chkEmpal;
    private javax.swing.JCheckBox chkGorengan;
    private javax.swing.JCheckBox chkIkan;
    private javax.swing.JCheckBox chkKentang;
    private javax.swing.JCheckBox chkKerang;
    private javax.swing.JCheckBox chkKerupuk;
    private javax.swing.JCheckBox chkKopi;
    private javax.swing.JCheckBox chkNasi;
    private javax.swing.JCheckBox chkTeh;
    private javax.swing.JCheckBox chkUdang;
    private javax.swing.JComboBox<String> cmbJumlahOrang;
    private javax.swing.JComboBox<String> cmbMeja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jmlAirMineral;
    private javax.swing.JTextField jmlAtiAmpela;
    private javax.swing.JTextField jmlAyam;
    private javax.swing.JTextField jmlCumi;
    private javax.swing.JTextField jmlEmpal;
    private javax.swing.JTextField jmlGorengan;
    private javax.swing.JTextField jmlIkan;
    private javax.swing.JTextField jmlKentang;
    private javax.swing.JTextField jmlKerang;
    private javax.swing.JTextField jmlKerupuk;
    private javax.swing.JTextField jmlKopi;
    private javax.swing.JTextField jmlNasi;
    private javax.swing.JTextField jmlTeh;
    private javax.swing.JTextField jmlUdang;
    private javax.swing.JLabel lblKembali;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JTextField qtyAirMineral;
    private javax.swing.JTextField qtyAtiAmpela;
    private javax.swing.JTextField qtyAyam;
    private javax.swing.JTextField qtyCumi;
    private javax.swing.JTextField qtyEmpal;
    private javax.swing.JTextField qtyGorengan;
    private javax.swing.JTextField qtyIkan;
    private javax.swing.JTextField qtyKentang;
    private javax.swing.JTextField qtyKerang;
    private javax.swing.JTextField qtyKerupuk;
    private javax.swing.JTextField qtyKopi;
    private javax.swing.JTextField qtyNasi;
    private javax.swing.JTextField qtyTeh;
    private javax.swing.JTextField qtyUdang;
    private javax.swing.JTextField txtAtasNama;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextArea txtCatatan;
    private javax.swing.JTextField txtNoPesanan;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    
    
    
    public void tampil(){
        TableNota.setValueAt(order.get(0), 0, 1);
        TableNota.setValueAt(order.get(1), 1, 1);
        TableNota.setValueAt(order.get(2), 2, 1);
        TableNota.setValueAt(order.get(3), 3, 1);
        TableNota.setValueAt(order.get(4), 4, 1);
        TableNota.setValueAt(order.get(5), 5, 1);
        TableNota.setValueAt(order.get(6), 6, 1);
        TableNota.setValueAt(order.get(7), 7, 1);
        TableNota.setValueAt(order.get(8), 8, 1);
        TableNota.setValueAt(order.get(9), 9, 1);
        TableNota.setValueAt(order.get(10), 10, 1);
        TableNota.setValueAt(order.get(11), 11, 1);
        TableNota.setValueAt(order.get(12), 12, 1);
        TableNota.setValueAt(order.get(13), 13, 1);
        TableNota.setValueAt(order.get(14), 14, 1);
        TableNota.setValueAt(order.get(15), 15, 1);
        TableNota.setValueAt(order.get(16), 16, 1);
        TableNota.setValueAt(order.get(17), 17, 1);
        TableNota.setValueAt(order.get(18), 18, 1);
        TableNota.setValueAt(order.get(19), 19, 1);
        TableNota.setValueAt("Nama", 0, 0);
        TableNota.setValueAt("Meja", 1, 0);
        TableNota.setValueAt("Nasi", 2, 0);
        TableNota.setValueAt("Ayam", 3, 0);
        TableNota.setValueAt("Kerang", 4, 0);
        TableNota.setValueAt("Ati Ampela", 5, 0);
        TableNota.setValueAt("Cumi", 6, 0);
        TableNota.setValueAt("Ikan", 7, 0);
        TableNota.setValueAt("Kentang", 8, 0);
        TableNota.setValueAt("Empal", 9,0);
        TableNota.setValueAt("Udang", 10, 0);
        TableNota.setValueAt("Air Mineral", 11, 0);
        TableNota.setValueAt("Teh", 12, 0);
        TableNota.setValueAt("Kopi", 13, 0);
        TableNota.setValueAt("Kerupuk", 14, 0);
        TableNota.setValueAt("Gorengan", 15, 0);
        TableNota.setValueAt("Total", 16, 0);
        TableNota.setValueAt("Bayar", 17, 0);
        TableNota.setValueAt("Kembalian", 18, 0);
        TableNota.setValueAt("Catatan", 19, 0);
    }
    
    public void clear(){
        TableNota.setValueAt("", 0, 1);
        TableNota.setValueAt("", 1, 1);
        TableNota.setValueAt("", 2, 1);
        TableNota.setValueAt("", 3, 1);
        TableNota.setValueAt("", 4, 1);
        TableNota.setValueAt("", 5, 1);
        TableNota.setValueAt("", 6, 1);
        TableNota.setValueAt("", 7, 1);
        TableNota.setValueAt("", 8, 1);
        TableNota.setValueAt("", 9, 1);
        TableNota.setValueAt("", 10, 1);
        TableNota.setValueAt("", 11, 1);
        TableNota.setValueAt("", 12, 1);
        TableNota.setValueAt("", 13, 1);
        TableNota.setValueAt("", 14, 1);
        TableNota.setValueAt("", 15, 1);
        TableNota.setValueAt("", 16, 1);
        TableNota.setValueAt("", 17, 1);
        TableNota.setValueAt("", 18, 1);
        TableNota.setValueAt("", 19, 1);
        TableNota.setValueAt("", 0, 0);
        TableNota.setValueAt("", 1, 0);
        TableNota.setValueAt("", 2, 0);
        TableNota.setValueAt("", 3, 0);
        TableNota.setValueAt("", 4, 0);
        TableNota.setValueAt("", 5, 0);
        TableNota.setValueAt("", 6, 0);
        TableNota.setValueAt("", 7, 0);
        TableNota.setValueAt("", 8, 0);
        TableNota.setValueAt("", 9,0);
        TableNota.setValueAt("", 10, 0);
        TableNota.setValueAt("", 11, 0);
        TableNota.setValueAt("", 12, 0);
        TableNota.setValueAt("", 13, 0);
        TableNota.setValueAt("", 14, 0);
        TableNota.setValueAt("", 15, 0);
        TableNota.setValueAt("", 16, 0);
        TableNota.setValueAt("", 17, 0);
        TableNota.setValueAt("", 18, 0);
        TableNota.setValueAt("", 19, 0);
    }
    
}